# Generated by Django 5.1.7 on 2025-03-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognition',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
